//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_C_
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSNV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HSNV()
        {
            this.QTCTs = new HashSet<QTCT>();
            this.QTDTs = new HashSet<QTDT>();
            this.NV_NGOAI_NGU = new HashSet<NV_NGOAI_NGU>();
        }
    
        public string ma_nv { get; set; }
        public string ho_ten { get; set; }
        public string ma_gioi_tinh { get; set; }
        public string ma_chuc_vu { get; set; }
        public string ma_dan_toc { get; set; }
        public string ma_ton_giao { get; set; }
        public System.DateTime ngay_sinh { get; set; }
        public string que_quan { get; set; }
        public string ma_noi_sinh { get; set; }
        public string dia_chi { get; set; }
        public string dien_thoai { get; set; }
        public string so_cccd { get; set; }
        public string ma_phong_ban { get; set; }
        public string ma_hoc_van { get; set; }
        public string ma_chuyen_mon { get; set; }
        public string vo_chong { get; set; }
        public string con { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual CHUYEN_MON CHUYEN_MON { get; set; }
        public virtual DAN_TOC DAN_TOC { get; set; }
        public virtual GIOI_TINH GIOI_TINH { get; set; }
        public virtual HOC_VAN HOC_VAN { get; set; }
        public virtual NOI_SINH NOI_SINH { get; set; }
        public virtual PHONG_BAN PHONG_BAN { get; set; }
        public virtual TON_GIAO TON_GIAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QTCT> QTCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QTDT> QTDTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_NGOAI_NGU> NV_NGOAI_NGU { get; set; }
    }
}
