//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_C_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSEntities : DbContext
    {
        public QLNSEntities()
            : base("name=QLNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<CHUYEN_MON> CHUYEN_MON { get; set; }
        public virtual DbSet<DAN_TOC> DAN_TOC { get; set; }
        public virtual DbSet<GIOI_TINH> GIOI_TINH { get; set; }
        public virtual DbSet<HINH_THUC> HINH_THUC { get; set; }
        public virtual DbSet<HOC_VAN> HOC_VAN { get; set; }
        public virtual DbSet<HSNV> HSNVs { get; set; }
        public virtual DbSet<NGANH_DT> NGANH_DT { get; set; }
        public virtual DbSet<NGOAI_NGU> NGOAI_NGU { get; set; }
        public virtual DbSet<NOI_SINH> NOI_SINH { get; set; }
        public virtual DbSet<NV_NGOAI_NGU> NV_NGOAI_NGU { get; set; }
        public virtual DbSet<PHONG_BAN> PHONG_BAN { get; set; }
        public virtual DbSet<QTCT> QTCTs { get; set; }
        public virtual DbSet<QTDT> QTDTs { get; set; }
        public virtual DbSet<TON_GIAO> TON_GIAO { get; set; }
        public virtual DbSet<TRUONG_DT> TRUONG_DT { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<XEP_LOAI> XEP_LOAI { get; set; }
    }
}
