//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_C_
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_NGOAI_NGU
    {
        public string ma_ngoai_ngu { get; set; }
        public string ma_nv { get; set; }
        public string ma_xep_loai { get; set; }
    
        public virtual HSNV HSNV { get; set; }
        public virtual NGOAI_NGU NGOAI_NGU { get; set; }
        public virtual XEP_LOAI XEP_LOAI { get; set; }
    }
}
