//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_C_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTCT
    {
        public string ma_qtct { get; set; }
        public string ma_nv { get; set; }
        public Nullable<System.DateTime> tu_ngay { get; set; }
        public Nullable<System.DateTime> den_ngay { get; set; }
        public string ma_phong_ban { get; set; }
        public string ma_chuc_vu { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual HSNV HSNV { get; set; }
        public virtual PHONG_BAN PHONG_BAN { get; set; }
    }
}
