//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_C_
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEP_LOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XEP_LOAI()
        {
            this.NV_NGOAI_NGU = new HashSet<NV_NGOAI_NGU>();
            this.QTDTs = new HashSet<QTDT>();
        }
    
        public string ma_xep_loai { get; set; }
        public string ten_xep_loai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_NGOAI_NGU> NV_NGOAI_NGU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QTDT> QTDTs { get; set; }
    }
}
